### PR TITLE
Implementation of condition result in LLD service/unit discovery

### PR DESCRIPTION
**Pull request by jangaraj**

### CODE REVIEW

**Comment by jangaraj** [comment]
@pastukhov please test this branch

**Comment by pastukhov** [comment]
No changes with new module version and new template.
Please tell, what exactly i should test.

**Comment by jangaraj** [comment]
Enabled services, which have `start condition failed` shouldn't be discovered anymore with provided example template (`ConditionResult` field/macro is now part of LLD discovery filter). For example this read-ahead service:
```
● systemd-readahead-collect.service - Collect Read-Ahead Data
   Loaded: loaded (/usr/lib/systemd/system/systemd-readahead-collect.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Fri 2017-06-23 20:33:23 BST; 1h 25min ago
           ConditionVirtualization=no was not met
     Docs: man:systemd-readahead-replay.service(8)
```

**Comment by pastukhov** [comment]
So, i need to delete this items and wait if it apear aganin?

**Comment by jangaraj** [comment]
Yes, that's one possible option to test it.

**Comment by krappix** [comment]
Hi, I'm testing this patch on Ubuntu 16.04 but I have no `{#SERVICE.CONDITIONRESULT}` entries in `zabbix_get -k systemd.service.discovery[service]` output.
Can it be that `ConditionResult` is a boolean and not a string and therefore is ignored?

**Comment by jangaraj** [comment]
No, you need to compile module from the `conditional-result` branch https://github.com/cavaliercoder/zabbix-module-systemd/tree/conditional-result This feature is still not available in the master branch.

**Comment by cavaliercoder** [comment]
Booleans should be returned as a Zabbix UI64 (https://github.com/cavaliercoder/zabbix-module-systemd/blob/master/src/modules/systemd/dbus.c#L300).

What happens if you run:
```
$ zabbix_get -k systemd.unit[sshd.service,org.freedesktop.systemd1.Unit,ConditionResult]
```

**Comment by jangaraj** [comment]
Item value is still UI64:
```
[root@dockerhost ~]# zabbix_get -s 127.0.0.1 -k systemd.unit[sshd.service,org.freedesktop.systemd1.Unit,ConditionResult]
ZBX_NOTSUPPORTED: failed to get property
[root@dockerhost ~]# zabbix_get -s 127.0.0.1 -k systemd.unit[sshd.service,Unit,ConditionResult]
1
```
But discovery value is string (I'm not sure if it should be integer there as well):
```
[root@dockerhost ~]# zabbix_get -s 127.0.0.1 -k systemd.service.discovery | jq .
...
    {
      "{#SERVICE.TYPE}": "service",
      "{#SERVICE.NAME}": "sshd.service",
      "{#SERVICE.CONDITIONRESULT}": "True",
      "{#SERVICE.DISPLAYNAME}": "OpenSSH server daemon",
      "{#SERVICE.PATH}": "/usr/lib/systemd/system/sshd.service",
      "{#SERVICE.STARTUPNAME}": "enabled"
    },
...
[root@dockerhost ~]# zabbix_get -s 127.0.0.1 -k systemd.unit.discovery[service] | jq . > delme
...
    {
      "{#UNIT.NAME}": "sshd.service",
      "{#UNIT.DESCRIPTION}": "OpenSSH server daemon",
      "{#UNIT.LOADSTATE}": "loaded",
      "{#UNIT.ACTIVESTATE}": "active",
      "{#UNIT.SUBSTATE}": "running",
      "{#UNIT.OBJECTPATH}": "/org/freedesktop/systemd1/unit/sshd_2eservice",
      "{#UNIT.FRAGMENTPATH}": "/usr/lib/systemd/system/sshd.service",
      "{#UNIT.UNITFILESTATE}": "enabled",
      "{#UNIT.CONDITIONRESULT}": "True"
    },
...
```

**Comment by krappix** [comment]
Hi,

@jangaraj I have compiled the module from the `conditional-result` branch.
@cavaliercoder On Ubuntu 16.04 output is similar but without `CONDITIONRESULT`:

```
(ssh) user@demo ‹ conditional-result › : ~/zabbix-module-systemd
[0] % zabbix_get -s 127.0.0.1 -k 'systemd.unit[ssh.service,Unit,ConditionResult]'
1
```

```
(ssh) user@demo ‹ conditional-result › : ~/zabbix-module-systemd
[0] % zabbix_get -s 127.0.0.1 -k 'systemd.service.discovery' | python -m json.tool
...
{
            "{#SERVICE.DISPLAYNAME}": "OpenBSD Secure Shell server",
            "{#SERVICE.NAME}": "ssh.service",
            "{#SERVICE.PATH}": "/lib/systemd/system/ssh.service",
            "{#SERVICE.STARTUPNAME}": "enabled",
            "{#SERVICE.TYPE}": "service"
},
...
```

```
(ssh) user@demo ‹ conditional-result › : ~/zabbix-module-systemd
[0] % zabbix_get -s 127.0.0.1 -k 'systemd.unit.discovery' | python -m json.tool
...
{
            "{#UNIT.ACTIVESTATE}": "active",
            "{#UNIT.DESCRIPTION}": "OpenBSD Secure Shell server",
            "{#UNIT.FRAGMENTPATH}": "/lib/systemd/system/ssh.service",
            "{#UNIT.LOADSTATE}": "loaded",
            "{#UNIT.NAME}": "ssh.service",
            "{#UNIT.OBJECTPATH}": "/org/freedesktop/systemd1/unit/ssh_2eservice",
            "{#UNIT.SUBSTATE}": "running",
            "{#UNIT.UNITFILESTATE}": "enabled"
},
...
```

**Comment by jangaraj** [comment]
Thx. I see that problem as well now. `dbus_get_property_json` returns FAIL. I didn't commit some my file :(. Give me some time to redevelop it again.

**Comment by jangaraj** [comment]
Support for Boolean values has been implemented - they are converted into yes/no strings (doc/template has been updated). That's systemctl behavior and I would like to be consistent with systemctl. 
```
zabbix_get -s 127.0.0.1 -k systemd.service.discovery | jq .
...
    {
      "{#SERVICE.TYPE}": "service",
      "{#SERVICE.NAME}": "systemd-hwdb-update.service",
      "{#SERVICE.DISPLAYNAME}": "Rebuild Hardware Database",
      "{#SERVICE.PATH}": "/usr/lib/systemd/system/systemd-hwdb-update.service",
      "{#SERVICE.STARTUPNAME}": "static",
      "{#SERVICE.CONDITIONRESULT}": "no"
    },
    {
      "{#SERVICE.TYPE}": "service",
      "{#SERVICE.NAME}": "plymouth-start.service",
      "{#SERVICE.DISPLAYNAME}": "Show Plymouth Boot Screen",
      "{#SERVICE.PATH}": "/usr/lib/systemd/system/plymouth-start.service",
      "{#SERVICE.STARTUPNAME}": "disabled",
      "{#SERVICE.CONDITIONRESULT}": "yes"
    },
...
zabbix_get -s 127.0.0.1 -k systemd.unit.discovery[service] | jq
...
    {
      "{#UNIT.NAME}": "iptables.service",
      "{#UNIT.DESCRIPTION}": "iptables.service",
      "{#UNIT.LOADSTATE}": "not-found",
      "{#UNIT.ACTIVESTATE}": "inactive",
      "{#UNIT.SUBSTATE}": "dead",
      "{#UNIT.OBJECTPATH}": "/org/freedesktop/systemd1/unit/iptables_2eservice",
      "{#UNIT.CONDITIONRESULT}": "no"
    },
    {
      "{#UNIT.NAME}": "systemd-tmpfiles-clean.service",
      "{#UNIT.DESCRIPTION}": "Cleanup of Temporary Directories",
      "{#UNIT.LOADSTATE}": "loaded",
      "{#UNIT.ACTIVESTATE}": "inactive",
      "{#UNIT.SUBSTATE}": "dead",
      "{#UNIT.OBJECTPATH}": "/org/freedesktop/systemd1/unit/systemd_2dtmpfiles_2dclean_2eservice",
      "{#UNIT.FRAGMENTPATH}": "/usr/lib/systemd/system/systemd-tmpfiles-clean.service",
      "{#UNIT.UNITFILESTATE}": "static",
      "{#UNIT.CONDITIONRESULT}": "yes"
    },
...
systemctl show sshd.service | grep ConditionResult
ConditionResult=yes
```
@krappix pls retest this branch

**Comment by krappix** [comment]
@jangaraj Thanks a lot, now it works.

**Pull request merged**
