### PR TITLE
Fix according to issue #5

### PR DESCRIPTION
**Pull request by pastukhov**
Fix according to issue #5

### CODE REVIEW

**Comment by jangaraj** [comment]
Did you test this code change?
README and example template should be updated as well.

**Comment by pastukhov** [comment]
I have compile module with this patch? but can't understand what changes i must made in template.

**Comment by cavaliercoder** [comment]
Thanks for taking the time to submit this. I'm concerned though, as the one-liner that I suggested in #5 is merely a suggestion on where to start - not a valid patch. Before we can action this idea, we need to throughly understand how the `Condition*` attributes work, which ones we need, how to interpret the values, etc. And then, as @jangaraj says, update README, examples, templates, testing, etc.

**Comment by jangaraj** [comment]
I'm closing this one, because it's not a valid solution.

For the record: it'll be easier for us to use `ConditionResult` - possible values are only: true/false
```
[root@dockerhost zabbix-module-systemd]# gdbus introspect --system --dest org.freedesktop.systemd1 --object-path /org/freedesktop/systemd1/unit/microcode_2eservice /org/freedesktop/systemd1/unit/microcode_2eservice  | grep Condition
      readonly b ConditionResult = false;
      readonly t ConditionTimestamp = 1498246406298513;
      readonly t ConditionTimestampMonotonic = 14596051;
      readonly a(sbbsi) Conditions = [('ConditionVirtualization', false, false, 'false', -1)];
[root@dockerhost zabbix-module-systemd]# gdbus introspect --system --dest org.freedesktop.systemd1 --object-path /org/freedesktop/systemd1/unit/sshd_2eservice /org/freedesktop/systemd1/unit/sshd_2eservice | grep Condition
      readonly b ConditionResult = true;
      readonly t ConditionTimestamp = 1498246412578631;
      readonly t ConditionTimestampMonotonic = 20876170;
      readonly a(sbbsi) Conditions = [];
```

Feel free to open another PR with tested code and updated doc. Or you can still wait for my implementation/improvements.

**Pull request closed without merging**
